name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main

jobs:
  laravel-build:
    runs-on: ubuntu-latest

    services:
      db-dl:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample_db
        ports:
          - 3306:3310
        options: >-
            --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          ref: main
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: ls -al
        run: |
          cd laravel_api_test
          ls -al

      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install

##      - name: Install dependencies
##        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Print php version
        run: |
          php -v

      - name: Set up Laravel environment
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: laravel-build
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/bisquebison1/www/
        