name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          ref: main
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install
        working-directory: ./src

      - name: set laravel env
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env
        working-directory: ./src

      - name: run unit test
        run: vendor/bin/phpunit tests/
        working-directory: ./src

  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/bisquebison1/www/
        