name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main

jobs:
  laravel-build:
    runs-on: ubuntu-latest
    container:
      image: php:8.0-fpm
      volumes:
        - /__w/docker-laravel-phpunit-githubaction/docker-laravel-phpunit-githubaction:/var/www

    services:
      db-dl:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample_db
        ports: 
          - 3306:3310
        options: >-
            --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Print php version
        run: |
          php -v

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Set up Laravel environment
        env:
          LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }}
        run: |
          cp .env.example .env
          sed -i "s/APP_ENV=local/APP_ENV=${LARAVEL_ENV}/" .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: laravel-build
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/bisquebison1/www/
        